In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import os
import random
import seaborn as sns
import warnings
warnings.filterwarnings("ignore")

In [3]:
pd.set_option("display.width",5000)
file=pd.read_csv("D:\Acmegrade\Files\pacific.csv")
file

             ID                 Name      Date  Time Event Status Latitude Longitude  Maximum Wind  Minimum Pressure  ...  Low Wind SW  Low Wind NW  Moderate Wind NE  Moderate Wind SE  Moderate Wind SW  Moderate Wind NW  High Wind NE  High Wind SE  High Wind SW  High Wind NW
0      EP011949              UNNAMED  19490611     0           TS    20.2N    106.3W            45              -999  ...         -999         -999              -999              -999              -999              -999          -999          -999          -999          -999
1      EP011949              UNNAMED  19490611   600           TS    20.2N    106.4W            45              -999  ...         -999         -999              -999              -999              -999              -999          -999          -999          -999          -999
2      EP011949              UNNAMED  19490611  1200           TS    20.2N    106.7W            45              -999  ...         -999         -999              -999              -999              -999              -999          -999          -999          -999          -999
3      EP011949              UNNAMED  19490611  1800           TS    20.3N    107.7W            45              -999  ...         -999         -999              -999              -999              -999              -999          -999          -999          -999          -999
4      EP011949              UNNAMED  19490612     0           TS    20.4N    108.6W            45              -999  ...         -999         -999              -999              -999              -999              -999          -999          -999          -999          -999
...         ...                  ...       ...   ...   ...    ...      ...       ...           ...               ...  ...          ...          ...               ...               ...               ...               ...           ...           ...           ...           ...
26132  EP222015               SANDRA  20151128  1200           LO    21.7N    109.0W            35              1002  ...            0            0                 0                 0                 0                 0             0             0             0             0
26133  EP222015               SANDRA  20151128  1800           LO    22.4N    108.7W            30              1007  ...            0            0                 0                 0                 0                 0             0             0             0             0
26134  EP222015               SANDRA  20151129     0           LO    23.1N    108.3W            30              1008  ...            0            0                 0                 0                 0                 0             0             0             0             0
26135  EP222015               SANDRA  20151129   600           LO    23.5N    107.9W            25              1009  ...            0            0                 0                 0                 0                 0             0             0             0             0
26136  EP222015               SANDRA  20151129  1200           LO    24.2N    107.7W            20              1010  ...            0            0                 0                 0                 0                 0             0             0             0             0

[26137 rows x 22 columns]

In [6]:
print(file.groupby("Status").agg({"Status":np.size}))

        Status
Status
 DB        217
 ET        152
 EX        110
 HU       6766
 LO       1828
 PT          6
 SD          4
 SS          7
 ST          6
 TD       6965
 TS      10076

In [9]:
file.Status=pd.Categorical(file.Status)
file["Status"]=file.Status.cat.codes

In [10]:
file

             ID                 Name      Date  Time Event  Status Latitude Longitude  Maximum Wind  Minimum Pressure  ...  Low Wind SW  Low Wind NW  Moderate Wind NE  Moderate Wind SE  Moderate Wind SW  Moderate Wind NW  High Wind NE  High Wind SE  High Wind SW  High Wind NW
0      EP011949              UNNAMED  19490611     0            10    20.2N    106.3W            45              -999  ...         -999         -999              -999              -999              -999              -999          -999          -999          -999          -999
1      EP011949              UNNAMED  19490611   600            10    20.2N    106.4W            45              -999  ...         -999         -999              -999              -999              -999              -999          -999          -999          -999          -999
2      EP011949              UNNAMED  19490611  1200            10    20.2N    106.7W            45              -999  ...         -999         -999              -999              -999              -999              -999          -999          -999          -999          -999
3      EP011949              UNNAMED  19490611  1800            10    20.3N    107.7W            45              -999  ...         -999         -999              -999              -999              -999              -999          -999          -999          -999          -999
4      EP011949              UNNAMED  19490612     0            10    20.4N    108.6W            45              -999  ...         -999         -999              -999              -999              -999              -999          -999          -999          -999          -999
...         ...                  ...       ...   ...   ...     ...      ...       ...           ...               ...  ...          ...          ...               ...               ...               ...               ...           ...           ...           ...           ...
26132  EP222015               SANDRA  20151128  1200             4    21.7N    109.0W            35              1002  ...            0            0                 0                 0                 0                 0             0             0             0             0
26133  EP222015               SANDRA  20151128  1800             4    22.4N    108.7W            30              1007  ...            0            0                 0                 0                 0                 0             0             0             0             0
26134  EP222015               SANDRA  20151129     0             4    23.1N    108.3W            30              1008  ...            0            0                 0                 0                 0                 0             0             0             0             0
26135  EP222015               SANDRA  20151129   600             4    23.5N    107.9W            25              1009  ...            0            0                 0                 0                 0                 0             0             0             0             0
26136  EP222015               SANDRA  20151129  1200             4    24.2N    107.7W            20              1010  ...            0            0                 0                 0                 0                 0             0             0             0             0

[26137 rows x 22 columns]

In [11]:
file_temp=file[:]
file_temp

             ID                 Name      Date  Time Event  Status Latitude Longitude  Maximum Wind  Minimum Pressure  ...  Low Wind SW  Low Wind NW  Moderate Wind NE  Moderate Wind SE  Moderate Wind SW  Moderate Wind NW  High Wind NE  High Wind SE  High Wind SW  High Wind NW
0      EP011949              UNNAMED  19490611     0            10    20.2N    106.3W            45              -999  ...         -999         -999              -999              -999              -999              -999          -999          -999          -999          -999
1      EP011949              UNNAMED  19490611   600            10    20.2N    106.4W            45              -999  ...         -999         -999              -999              -999              -999              -999          -999          -999          -999          -999
2      EP011949              UNNAMED  19490611  1200            10    20.2N    106.7W            45              -999  ...         -999         -999              -999              -999              -999              -999          -999          -999          -999          -999
3      EP011949              UNNAMED  19490611  1800            10    20.3N    107.7W            45              -999  ...         -999         -999              -999              -999              -999              -999          -999          -999          -999          -999
4      EP011949              UNNAMED  19490612     0            10    20.4N    108.6W            45              -999  ...         -999         -999              -999              -999              -999              -999          -999          -999          -999          -999
...         ...                  ...       ...   ...   ...     ...      ...       ...           ...               ...  ...          ...          ...               ...               ...               ...               ...           ...           ...           ...           ...
26132  EP222015               SANDRA  20151128  1200             4    21.7N    109.0W            35              1002  ...            0            0                 0                 0                 0                 0             0             0             0             0
26133  EP222015               SANDRA  20151128  1800             4    22.4N    108.7W            30              1007  ...            0            0                 0                 0                 0                 0             0             0             0             0
26134  EP222015               SANDRA  20151129     0             4    23.1N    108.3W            30              1008  ...            0            0                 0                 0                 0                 0             0             0             0             0
26135  EP222015               SANDRA  20151129   600             4    23.5N    107.9W            25              1009  ...            0            0                 0                 0                 0                 0             0             0             0             0
26136  EP222015               SANDRA  20151129  1200             4    24.2N    107.7W            20              1010  ...            0            0                 0                 0                 0                 0             0             0             0             0

[26137 rows x 22 columns]

In [12]:
file_temp.drop(["ID"],axis=1,inplace=True)
file_temp.drop(["Name"],axis=1,inplace=True)
file_temp.drop(["Date"],axis=1,inplace=True)
file_temp.drop(["Time"],axis=1,inplace=True)
file_temp.drop(["Event"],axis=1,inplace=True)
file_temp.drop(["Status"],axis=1,inplace=True)
file_temp.drop(["Latitude"],axis=1,inplace=True)
file_temp.drop(["Longitude"],axis=1,inplace=True)

In [13]:
file_temp

       Maximum Wind  Minimum Pressure  Low Wind NE  Low Wind SE  Low Wind SW  Low Wind NW  Moderate Wind NE  Moderate Wind SE  Moderate Wind SW  Moderate Wind NW  High Wind NE  High Wind SE  High Wind SW  High Wind NW
0                45              -999         -999         -999         -999         -999              -999              -999              -999              -999          -999          -999          -999          -999
1                45              -999         -999         -999         -999         -999              -999              -999              -999              -999          -999          -999          -999          -999
2                45              -999         -999         -999         -999         -999              -999              -999              -999              -999          -999          -999          -999          -999
3                45              -999         -999         -999         -999         -999              -999              -999              -999              -999          -999          -999          -999          -999
4                45              -999         -999         -999         -999         -999              -999              -999              -999              -999          -999          -999          -999          -999
...             ...               ...          ...          ...          ...          ...               ...               ...               ...               ...           ...           ...           ...           ...
26132            35              1002           60            0            0            0                 0                 0                 0                 0             0             0             0             0
26133            30              1007            0            0            0            0                 0                 0                 0                 0             0             0             0             0
26134            30              1008            0            0            0            0                 0                 0                 0                 0             0             0             0             0
26135            25              1009            0            0            0            0                 0                 0                 0                 0             0             0             0             0
26136            20              1010            0            0            0            0                 0                 0                 0                 0             0             0             0             0

[26137 rows x 14 columns]

In [14]:
x=file_temp.values
x

array([[  45, -999, -999, ..., -999, -999, -999],
       [  45, -999, -999, ..., -999, -999, -999],
       [  45, -999, -999, ..., -999, -999, -999],
       ...,
       [  30, 1008,    0, ...,    0,    0,    0],
       [  25, 1009,    0, ...,    0,    0,    0],
       [  20, 1010,    0, ...,    0,    0,    0]], dtype=int64)

In [15]:
y=file["Status"].values
y

array([10, 10, 10, ...,  4,  4,  4], dtype=int8)

In [16]:
from sklearn.model_selection import train_test_split as tts
x_train, x_test, y_train, y_test= tts(x,y, test_size=0.4)

In [17]:
print(x_train.shape, x_test.shape, y_train.shape, y_test.shape)

(15682, 14) (10455, 14) (15682,) (10455,)

In [19]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score as asc
lr=LogisticRegression()
lr.fit(x_train,y_train)
lr_pred=lr.predict(x)
acc_lr=asc(y,lr_pred)
print(acc_lr)

0.7543711979186594

In [22]:
from sklearn.neighbors import KNeighborsClassifier
knc=KNeighborsClassifier(n_neighbors=100, metric="minkowski", p=2)
knc.fit(x_train,y_train)
knc_pred=knc.predict(x)
acc_knc=asc(y,knc_pred)
print(acc_knc)

0.9505299001415618